button component
devAmlan/Mlan-UI pull request #2
Opened 2022-02-04 18:26 UTC by devAmlan

This is the button component. Please review my PR.

2022-02-04 18:49 UTC, developer-anand approved these changes
Good work man

2022-02-05 07:30 UTC, zoef-yt requested changes

2022-02-05 07:30 UTC, zoef-yt commented on library/component/button/button.css
> +      padding:0.5rem 2.1rem;
use px here

2022-02-05 07:30 UTC, zoef-yt commented on library/component/button/button.css
> +    padding:0.5rem 2.1rem;
use px here

2022-02-05 13:41 UTC, devAmlan commented on library/component/button/button.css
> +      padding:0.5rem 2.1rem;
done,  thanks zoef

2022-02-05 13:47 UTC, merged